#!/bin/sh

DEVICE="HB-GARAGE-SenAct-2-1-SC"
DEVICE_IMG=hb-garage-senact-2-1-sc.png
DEVICE_THUMB=hb-garage-senact-2-1-sc_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-garage-senact-2-1-sc.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
